before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev curl wget
language: ruby
cache: bundler
bundler_args: --without development
script:
  - bundle exec rake spec:ci
  - bundle exec rake rubocop
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - 2.1.10
  - rbx-3
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-3
