before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev curl wget
language: ruby
bundler_args: --without development
script: "bundle exec rake spec:ci"
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
  - 2.0.0
  - 1.9.3
  - rbx
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
