before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libmagic-dev curl wget
language: ruby
bundler_args: --without development
script: "bundle exec rake spec:ci"
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.10
  - rbx-2
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx-2
