language: ruby
bundler_args: --without development
script: "bundle exec rake spec:ci"
env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
rvm:
  - 2.2.2
  - 2.1.6
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx
gemfile:
  - Gemfile
notifications:
  recipients:
    - xeron.oskom@gmail.com
